version: '3'

volumes:
  holistiplan_local_postgres_data: {}
  holistiplan_local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: holistiplan_local_django
    container_name: django
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: holistiplan_production_postgres
    container_name: postgres
    volumes:
      - holistiplan_local_postgres_data:/var/lib/postgresql/data
      - holistiplan_local_postgres_data_backups:/backups
    ports:
      - '5432:5432'
    env_file:
      - ./.envs/.local/.postgres

  redis:
    image: redis:6
    container_name: redis
    ports:
      - '6379:6379'

  celeryworker:
    <<: *django
    image: holistiplan_local_celeryworker
    container_name: worker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: holistiplan_local_celerybeat
    container_name: celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat

  node:
    build:
      context: .
      dockerfile: ./compose/local/node/Dockerfile
    image: holistiplan_local_node
    container_name: node
    depends_on:
      - django
    volumes:
      - .:/app:z
      # http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
      - /app/node_modules
    command: npm run dev
    ports:
      - '3000:3000'

  vite:
    build:
      context: .
      dockerfile: ./compose/local/vite/Dockerfile
    image: my_awesome_vue_project_local_vite
    container_name: vite
    depends_on:
      - django
    volumes:
      - .:/app:z
      - /app/vue_frontend/node_modules
    command: vite dev
    ports:
      - '5173:5173'
